version: '3.8'

services:
  node-app:
    image: node:20-alpine
    container_name: CinefiloDelCazzoBE
    working_dir: ./
    volumes:
      - ./node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=100
    command: npm start
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.5'
        reservations:
          memory: 100M
          cpus: '0.25'