name: Monorepo Build and Deploy

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '24'
  VITE_BASE_API: "cinefilo"
  VITE_DOMAIN: "edoardohorse.ovh"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install all dependencies
        run: npm ci

      - name: Build frontend
        run: |
          # Create a .env file during build
          echo "VITE_BASE_API=$VITE_BASE_API" >> .env
          echo "VITE_DOMAIN=$VITE_DOMAIN" >> .env
          cat .env
          # Run your build command
          npm run build

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/


  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
